# Generated by Django 2.0.13 on 2019-04-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('nrofono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('colegio', models.CharField(max_length=20)),
                ('ciudad', models.CharField(blank=True, choices=[('Arica', 'Arica'), ('Iquique', 'Iquique'), ('Chillan', 'Chillan'), ('Santiago', 'Santiago'), ('Concepcion', 'Concepcion'), ('Otra', 'Otra ciudad')], max_length=20)),
                ('carrera_post_1', models.CharField(blank=True, choices=[('AGRO', 'Agronomia'), ('CON_AUD', 'Contador Auditor'), ('ED_PARV', 'Educacion Parvularia'), ('ENF', 'Enfermeria'), ('ING_CIV_INF', 'Ing. Civil en Informatica'), ('ING_INF', 'Ing. Informatica'), ('ING_COM', 'Ing. Comercial'), ('ING_ELEC', 'Ing. en Electronica y Telecomunicaciones'), ('ING_CIV_IND', 'Ingenieria Civil Industrial'), ('NUT', 'Nutricion y Dietetica'), ('OBS', 'Obstetricia y Puericultura'), ('PED_BIO', 'Ped. en Biologia'), ('PED_ED_DIF', 'Ped. en Educ. Diferencial m/DEA'), ('PED_ED_FIS', 'Ped. en Educacion Fisica'), ('PED_ED_GEN_BAS', 'Ped. en Educacion General Basica'), ('PED_HIS', 'Ped. en Historia y Geografia'), ('PED_ING', 'Ped. en Ingles'), ('PED_LENG', 'Ped. en Lengua Castellana y Comunicacion'), ('PED_MAT', 'Ped. en Matematica y Computacion'), ('PED_MUS', 'Ped. en Musica m/ Educacion Extraescolar'), ('PSICO', 'Psicologia'), ('TEO', 'Teologia'), ('TNS_ENF', 'TNS en Enfermeria'), ('TRAB_SOC', 'Trabajo Social')], max_length=50)),
                ('carrera_post_2', models.CharField(blank=True, choices=[('AGRO', 'Agronomia'), ('CON_AUD', 'Contador Auditor'), ('ED_PARV', 'Educacion Parvularia'), ('ENF', 'Enfermeria'), ('ING_CIV_INF', 'Ing. Civil en Informatica'), ('ING_INF', 'Ing. Informatica'), ('ING_COM', 'Ing. Comercial'), ('ING_ELEC', 'Ing. en Electronica y Telecomunicaciones'), ('ING_CIV_IND', 'Ingenieria Civil Industrial'), ('NUT', 'Nutricion y Dietetica'), ('OBS', 'Obstetricia y Puericultura'), ('PED_BIO', 'Ped. en Biologia'), ('PED_ED_DIF', 'Ped. en Educ. Diferencial m/DEA'), ('PED_ED_FIS', 'Ped. en Educacion Fisica'), ('PED_ED_GEN_BAS', 'Ped. en Educacion General Basica'), ('PED_HIS', 'Ped. en Historia y Geografia'), ('PED_ING', 'Ped. en Ingles'), ('PED_LENG', 'Ped. en Lengua Castellana y Comunicacion'), ('PED_MAT', 'Ped. en Matematica y Computacion'), ('PED_MUS', 'Ped. en Musica m/ Educacion Extraescolar'), ('PSICO', 'Psicologia'), ('TEO', 'Teologia'), ('TNS_ENF', 'TNS en Enfermeria'), ('TRAB_SOC', 'Trabajo Social')], max_length=50)),
                ('carrera_post_3', models.CharField(blank=True, choices=[('AGRO', 'Agronomia'), ('CON_AUD', 'Contador Auditor'), ('ED_PARV', 'Educacion Parvularia'), ('ENF', 'Enfermeria'), ('ING_CIV_INF', 'Ing. Civil en Informatica'), ('ING_INF', 'Ing. Informatica'), ('ING_COM', 'Ing. Comercial'), ('ING_ELEC', 'Ing. en Electronica y Telecomunicaciones'), ('ING_CIV_IND', 'Ingenieria Civil Industrial'), ('NUT', 'Nutricion y Dietetica'), ('OBS', 'Obstetricia y Puericultura'), ('PED_BIO', 'Ped. en Biologia'), ('PED_ED_DIF', 'Ped. en Educ. Diferencial m/DEA'), ('PED_ED_FIS', 'Ped. en Educacion Fisica'), ('PED_ED_GEN_BAS', 'Ped. en Educacion General Basica'), ('PED_HIS', 'Ped. en Historia y Geografia'), ('PED_ING', 'Ped. en Ingles'), ('PED_LENG', 'Ped. en Lengua Castellana y Comunicacion'), ('PED_MAT', 'Ped. en Matematica y Computacion'), ('PED_MUS', 'Ped. en Musica m/ Educacion Extraescolar'), ('PSICO', 'Psicologia'), ('TEO', 'Teologia'), ('TNS_ENF', 'TNS en Enfermeria'), ('TRAB_SOC', 'Trabajo Social')], max_length=50)),
            ],
        ),
    ]
