# Generated by Django 2.0.13 on 2019-04-14 14:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='anioegreso',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='formulario',
            name='aniopost',
            field=models.CharField(choices=[('PRIMERO', '1° medio'), ('SEGUNDO', '2° medio'), ('TERCERO', '3° medio'), ('CUARTO', '4° medio'), ('OTRO', 'Ya egresé')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='rut',
            field=models.CharField(default=0, help_text='Tu RUT sin puntos y con guión', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulario',
            name='carrera_post_1',
            field=models.CharField(choices=[('AGRO', 'Agronomía'), ('CON_AUD', 'Contador Auditor'), ('ED_PARV', 'Educación Parvularia'), ('ENF', 'Enfermería'), ('ING_COM', 'Ingeniería Comercial'), ('ING_INF', 'Ingeniería Informática'), ('ING_ELEC', 'Ingeniería en Electrónica y Telecomunicaciones'), ('ING_CIV_IND', 'Ingeniería Civil Industrial'), ('ING_CIV_INF', 'Ingeniería Civil Informática'), ('NUT', 'Nutrición y Dietética'), ('OBS', 'Obstetricia y Puericultura'), ('PED_BIO', 'Pedagogía en Biología'), ('PED_ED_DIF', 'Pedagogía en Educación Diferencial'), ('PED_ED_FIS', 'Pedagogía en Educación Física'), ('PED_ED_GEN_BAS', 'Pedagogía en Educación General Básica'), ('PED_HIS', 'Pedagogía en Historia y Geografia'), ('PED_ING', 'Pedagogía en Inglés'), ('PED_LENG', 'Pedagogía en Lengua Castellana y Comunicacion'), ('PED_MAT', 'Pedagogía en Matemática y Computacion'), ('PED_MUS', 'Pedagogía en Música'), ('PSICO', 'Psicología'), ('TEO', 'Teología'), ('TNS_ENF', 'TENS en Enfermería'), ('TRAB_SOC', 'Trabajo Social')], max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='carrera_post_2',
            field=models.CharField(blank=True, choices=[('AGRO', 'Agronomía'), ('CON_AUD', 'Contador Auditor'), ('ED_PARV', 'Educación Parvularia'), ('ENF', 'Enfermería'), ('ING_COM', 'Ingeniería Comercial'), ('ING_INF', 'Ingeniería Informática'), ('ING_ELEC', 'Ingeniería en Electrónica y Telecomunicaciones'), ('ING_CIV_IND', 'Ingeniería Civil Industrial'), ('ING_CIV_INF', 'Ingeniería Civil Informática'), ('NUT', 'Nutrición y Dietética'), ('OBS', 'Obstetricia y Puericultura'), ('PED_BIO', 'Pedagogía en Biología'), ('PED_ED_DIF', 'Pedagogía en Educación Diferencial'), ('PED_ED_FIS', 'Pedagogía en Educación Física'), ('PED_ED_GEN_BAS', 'Pedagogía en Educación General Básica'), ('PED_HIS', 'Pedagogía en Historia y Geografia'), ('PED_ING', 'Pedagogía en Inglés'), ('PED_LENG', 'Pedagogía en Lengua Castellana y Comunicacion'), ('PED_MAT', 'Pedagogía en Matemática y Computacion'), ('PED_MUS', 'Pedagogía en Música'), ('PSICO', 'Psicología'), ('TEO', 'Teología'), ('TNS_ENF', 'TENS en Enfermería'), ('TRAB_SOC', 'Trabajo Social')], max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='carrera_post_3',
            field=models.CharField(blank=True, choices=[('AGRO', 'Agronomía'), ('CON_AUD', 'Contador Auditor'), ('ED_PARV', 'Educación Parvularia'), ('ENF', 'Enfermería'), ('ING_COM', 'Ingeniería Comercial'), ('ING_INF', 'Ingeniería Informática'), ('ING_ELEC', 'Ingeniería en Electrónica y Telecomunicaciones'), ('ING_CIV_IND', 'Ingeniería Civil Industrial'), ('ING_CIV_INF', 'Ingeniería Civil Informática'), ('NUT', 'Nutrición y Dietética'), ('OBS', 'Obstetricia y Puericultura'), ('PED_BIO', 'Pedagogía en Biología'), ('PED_ED_DIF', 'Pedagogía en Educación Diferencial'), ('PED_ED_FIS', 'Pedagogía en Educación Física'), ('PED_ED_GEN_BAS', 'Pedagogía en Educación General Básica'), ('PED_HIS', 'Pedagogía en Historia y Geografia'), ('PED_ING', 'Pedagogía en Inglés'), ('PED_LENG', 'Pedagogía en Lengua Castellana y Comunicacion'), ('PED_MAT', 'Pedagogía en Matemática y Computacion'), ('PED_MUS', 'Pedagogía en Música'), ('PSICO', 'Psicología'), ('TEO', 'Teología'), ('TNS_ENF', 'TENS en Enfermería'), ('TRAB_SOC', 'Trabajo Social')], max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='ciudad',
            field=models.CharField(choices=[('Arica', 'Arica'), ('Iquique', 'Iquique'), ('Chillan', 'Chillán'), ('Santiago', 'Santiago'), ('Concepcion', 'Concepción'), ('Otra', 'Otra ciudad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nrofono',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Los 8 dígitos luego del +569', max_length=128, region=None),
        ),
    ]
