# Generated by Django 2.2 on 2019-04-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190414_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='ciudad',
            field=models.CharField(choices=[('', 'Escoge una ciudad...'), ('ARICA', 'Arica'), ('IQUIQUE', 'Iquique'), ('CALAMA', 'Calama'), ('ANTOFAGASTA', 'Antofagasta'), ('COPIAPO', 'Copiapó'), ('LASERENA', 'La Serena'), ('QUILPUE', 'Quilpué'), ('SANTIAGO', 'Santiago'), ('MOLINA', 'Molina'), ('TALCA', 'Talca'), ('CHILLAN', 'Chillán'), ('LOTA', 'Lota'), ('TALCAHUANO', 'Talcahuano'), ('CONCEPCION', 'Concepción'), ('LOSANGELES', 'Los Ángeles'), ('ANGOL', 'Angol'), ('TEMUCO', 'Temuco'), ('PITRUFQUEN', 'Pitrufquén'), ('VILLARRICA', 'Villarrica'), ('VALDIVIA', 'Valdivia'), ('PUNTAARENAS', 'Punta Arenas'), ('LINARES', 'Linares'), ('PARRAL', 'Parral'), ('NINHUE', 'Ninhue'), ('QUIRIHUE', 'Quirihue'), ('CHILLANVIEJO', 'Chillán Viejo'), ('BULNES', 'Bulnes'), ('SANCARLOS', 'San Carlos'), ('SANIGNACIO', 'San Ignacio'), ('ELCARMEN', 'El Carmen'), ('SANNICOLAS', 'San Nicolás'), ('PINTO', 'Pinto'), ('COIHUECO', 'Coihueco'), ('ÑIQUEN', 'Ñiquén'), ('QUILLON', 'Quillón'), ('YUNGAY', 'Yungay')], max_length=20),
        ),
    ]
