# Generated by Django 2.2 on 2019-04-16 18:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190416_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='nrofono',
            field=phonenumber_field.modelfields.PhoneNumberField(default='9', help_text='Los 8 dígitos luego del +569', max_length=128, region=None),
        ),
    ]
